apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shermandemogoogle-wild
  #namespace: cert-manager
spec:
  secretName: shermandemogoogle-wild-tls
  issuerRef:
    # The issuer created previously
    name: dns-example-issuer
    kind: ClusterIssuer
  dnsNames:
  - foo.shermandemogoogle.com 
